# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: gomod
    open-pull-requests-limit: 5
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
        - "actions/*"
        - "github/codeql-action"
      docker:
        patterns:
        - "docker/*"
