# See: https://taskfile.dev/api/

version: "3"

tasks:
  default:
    cmds:
      - task: sync
  dev:
    desc: "Install all needed tools for development"
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go install github.com/kisielk/errcheck@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  sync:
    desc: "Sync all packages"
    cmds:
      - go work sync
      - go work vendor


  build-images:
    desc: "Build MS images (buider and production)"
    cmds:
      - docker buildx build --file .docker/builder/Dockerfile . --build-arg "GITHUB_USERNAME=$GITLAB_USERNAME" --build-arg "GITHULAB_PAT=$GITLAB_PAT" --tag "kitanoyoru/kitadrivebot.v1.builder:latest"
      - docker buildx build --file apps/sso/Dockerfile . --tag "kitanoyoru/kitadrivebot.v1.sso:latest"
