// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kitanoyoru/kitaDriveBot/internal/usecase (interfaces: DriveRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/drive_repository.go -package=mocks github.com/kitanoyoru/kitaDriveBot/internal/usecase DriveRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/kitanoyoru/kitaDriveBot/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDriveRepository is a mock of DriveRepository interface.
type MockDriveRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDriveRepositoryMockRecorder
	isgomock struct{}
}

// MockDriveRepositoryMockRecorder is the mock recorder for MockDriveRepository.
type MockDriveRepositoryMockRecorder struct {
	mock *MockDriveRepository
}

// NewMockDriveRepository creates a new mock instance.
func NewMockDriveRepository(ctrl *gomock.Controller) *MockDriveRepository {
	mock := &MockDriveRepository{ctrl: ctrl}
	mock.recorder = &MockDriveRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriveRepository) EXPECT() *MockDriveRepositoryMockRecorder {
	return m.recorder
}

// EnsureFolderPath mocks base method.
func (m *MockDriveRepository) EnsureFolderPath(ctx context.Context, path domain.FolderPath) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureFolderPath", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureFolderPath indicates an expected call of EnsureFolderPath.
func (mr *MockDriveRepositoryMockRecorder) EnsureFolderPath(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureFolderPath", reflect.TypeOf((*MockDriveRepository)(nil).EnsureFolderPath), ctx, path)
}

// UploadPDF mocks base method.
func (m *MockDriveRepository) UploadPDF(ctx context.Context, folderID, name string, content io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPDF", ctx, folderID, name, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPDF indicates an expected call of UploadPDF.
func (mr *MockDriveRepositoryMockRecorder) UploadPDF(ctx, folderID, name, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPDF", reflect.TypeOf((*MockDriveRepository)(nil).UploadPDF), ctx, folderID, name, content)
}
