// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kitanoyoru/kitaDriveBot/internal/usecase (interfaces: FileFetcher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/file_fetcher.go -package=mocks github.com/kitanoyoru/kitaDriveBot/internal/usecase FileFetcher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileFetcher is a mock of FileFetcher interface.
type MockFileFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockFileFetcherMockRecorder
	isgomock struct{}
}

// MockFileFetcherMockRecorder is the mock recorder for MockFileFetcher.
type MockFileFetcherMockRecorder struct {
	mock *MockFileFetcher
}

// NewMockFileFetcher creates a new mock instance.
func NewMockFileFetcher(ctrl *gomock.Controller) *MockFileFetcher {
	mock := &MockFileFetcher{ctrl: ctrl}
	mock.recorder = &MockFileFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileFetcher) EXPECT() *MockFileFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockFileFetcher) Fetch(ctx context.Context, fileID string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, fileID)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockFileFetcherMockRecorder) Fetch(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockFileFetcher)(nil).Fetch), ctx, fileID)
}
