version: "3"

networks:
  default:
    name: kitaDriveBot 
    external: true

services:
  migrate-up:
    image: ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
    environment:
      SQL_CONNECTION_STRING: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/kita?sslmode=disable
    command:
      - migrate
      - up
    depends_on:
      - crdb 

  crdb:
    image: cockroachdb/cockroach:v19.2.2
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure

  redis:
    image: redis:6.2-alpine
    command: redis-server --appendonly yes --requirepass yourStrongPassword!123
    ports:
      - "6379:6379"
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - app_network

  redis-sentinel:
    image: redis:6.2-alpine
    depends_on:
      - redis
    entrypoint: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./config/redis-sentinel.conf:/usr/local/etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    restart: always
