version: "3"

networks:
  default:
    name: kitaDriveBot 
    external: true

services:
  migrate-up:
    image: ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
    environment:
      SQL_CONNECTION_STRING: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/kitadrivebot.v1.sso?sslmode=disable
    command:
      - migrate
      - up
    depends_on:
      - crdb 

  crdb:
    image: cockroachdb/cockroach:v19.2.2
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
